version: '3.8'
services:
  postgres:
    container_name: webinar-postgres
    image: postgres:12.13-bullseye
    restart: always
    environment:
      PGDATA: /var/lib/data/postgres
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - postgres:/var/lib/data/postgres
      - pgback:/var/lib/data/backup
    ports: 
      - "5432:5432"
  backend:
    image: mmladshev/webinartest
    restart: always
  nginx:
    image: nginx:latest
    depends_on:
      - backend
    ports:
      - "80:80"
    command: |
      bash -c 'bash -s <<EOF
        cat > /etc/nginx/conf.d/default.conf <<EON
          server {
              listen 80;
              server_name localhost;
              location / {
                  proxy_pass http://backend:80;
              }
          }
      EON
      nginx -g "daemon off;";
      EOF'

volumes: 
  postgres:
  pgback:
